!!brut.androlib.meta.MetaInfo
apkFileName: Meid Pro_1.0.9.apk
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '21'
  targetSdkVersion: '33'
  maxSdkVersion: null
sharedLibrary: false
sparseResources: false
unknownFiles: {}
usesFramework:
  ids: []
versionInfo:
  versionCode: '1'
  versionName: '1.0.9'
